name: CI/CD Pipeline for Cars Website

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js (if frontend is React/Vue)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies (for Node.js projects)
        run: npm install
        continue-on-error: true

      - name: Lint Code
        run: npm run lint || echo "Linting failed, check code"

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=car_project \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 (or S3)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Deploying to EC2 or S3..."
          # If deploying to EC2:
          # scp -i your-key.pem -r * ec2-user@your-ec2-ip:/var/www/html/
          
          # If deploying to S3:
          # aws s3 sync . s3://your-bucket-name --delete
